branch-defaults:
  svg:
    environment: null
    group_suffix: null
global:
  application_name: grubscore
  default_ec2_keyname: null
  default_platform: Ruby 2.3.0
  default_region: us-west-2
  profile: eb-cli
  sc: git
